
name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: 🛎️ checkout source
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: 🎁 download lfs objects
      run: git lfs checkout

    - name: 🔧 setup node
      uses: actions/setup-node@v1
      with:
        node-version: 17

    - name: 📦 install dependencies
      shell: bash
      run: npm i

    - name: 🏃‍♂️ build
      shell: bash
      run: npm run build
