
name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: 🛎️ checkout source
      uses: actions/checkout@v2
      with:
        lfs: false

    - name: 🔧 setup node
      uses: actions/setup-node@v1
      with:
        node-version: "17"

    - name: 📦 install dependencies
      shell: bash
      run: npm i

    - name: 🏃‍♂️ typescript compile
      shell: bash
      run: npm run compile-typescript
