
name: release to gh-pages
on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - name: 🛎️ checkout source
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: 🎁 download lfs objects
      run: git lfs checkout

    - name: 🔧 setup node
      uses: actions/setup-node@v1
      with:
        node-version: 17

    - name: 📦 install dependencies
      shell: bash
      run: npm ci

    - name: 🏃‍♂️ build
      shell: bash
      run: npm run build

    - name: 🗃️ copy node_modules
      shell: bash
      run: npm ci --production && rm -rf x/node_modules x/s && cp -r node_modules/ x/ && rm -rf x/assets && cp -r assets/ x/

    - name: 🚀 gh-pages deployment
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: x
        single-commit: true
